### ISSUE TITLE
Crash soon after started

### ISSUE THREAD

**Issue by huanglu2018** [gymreklab/GangSTR#100]
I aligned my RNAseq data using STAR, and ran GangSTR with default settings, which resulted an error as follows: 

```
[GangSTR-2.4] ProgressMeter: Loading read group id g1 for sample s1
[GangSTR-2.4] ProgressMeter: Processing chr1:14070
[GangSTR-2.4] ProgressMeter: 	Genotyper Results:  3, 3	likelihood = 9.24477
[GangSTR-2.4] ProgressMeter: Processing chr1:16620
....
[GangSTR-2.4] ProgressMeter: Processing chr1:948423
[GangSTR-2.4] ProgressMeter: 	Genotyper Results:  1, 1	likelihood = -25
[GangSTR-2.4] ProgressMeter: Processing chr1:948930
[GangSTR-2.4] ERROR: Invalid CIGAR option encountered in TrimAlignment
```

when I use a bwa-aligned bam file, the error message disappeared. so this might be caused by the aligner. 
my STAR options are:

    STAR --genomeDir $star_genome_dir \
    --readFilesIn $fq1 $fq2 \
    --runThreadN $threads \
    --limitBAMsortRAM 0 \
    --readFilesCommand zcat \
    --outSAMtype BAM SortedByCoordinate \
    --outFileNamePrefix $outdir \
    --outFilterMultimapScoreRange 1 \
    --outFilterMultimapNmax 20 \
    --outFilterMismatchNmax 10 \
    --alignIntronMax 500000 \
    --alignMatesGapMax 1000000 \
    --sjdbScore 2 \
    --alignSJDBoverhangMin 1 \
    --genomeLoad NoSharedMemory \
    --outFilterMatchNminOverLread 0.33 \
    --outFilterScoreMinOverLread 0.33 \
    --sjdbOverhang 100 \
    --outSAMstrandField intronMotif \
    --outSAMattributes NM MD MC AS XS \
    --outSAMunmapped Within \
    --outTmpDir $tmp_dir \
    --outSAMattrRGline ID:$id LB:$id SM:$id PL:Illumina PU:$id

Is there a way to use STAR-aligned bam as input?

**Comment by nmmsv** [comment]
Apologies for my late response!
Currently, GangSTR only supports DNA sequencing data (preferably PCR-free whole genome sequencing). RNA seq includes large gaps in alignment that our software does not support.
Please reopen this issue if you had any other questions.
Thanks!
Nima
