### ISSUE TITLE
Pre-defined off-target loci for target pathogenic loci links are not working

### ISSUE THREAD

**Issue by SergeyPhys** [gymreklab/GangSTR#31]
Hi Nima,

Many thanks for the nice tool!

Can you please check the following links, which currently don't work?
SCA2 | SCA2_hg38.bed
SCA3 | SCA3_hg38.bed
SCA6 | SCA6_hg38.bed
SCA7 | SCA7_hg38.bed
SCA8 | SCA8_hg38.bed
SCA12 | SCA12_hg38.bed
SCA17 | SCA17_hg38.bed
HTT | HTT_hg38.bed
DM1 | DM1_hg38.bed

Many thanks,
Sergey

**Comment by nmmsv** [comment]
Hi Sergey,
Thanks for pointing this out, we've fixed the links. Please let me know if the download links work on your end, and I'll close this issue.
Best,
Nima

**Comment by SergeyPhys** [comment]
Hi Nima,

The links are now working. Thank you for fixing it.

Kind regards,
Sergey

**Comment by nmmsv** [comment]
Perfect! Thanks.
