### ISSUE TITLE
Erroneuos results: GB value lies outside of the confidence interval and is unreasonably high

### ISSUE THREAD

**Issue by Matthlas** [gymreklab/GangSTR#32]
Hey,

first of all thanks again for the nice tool!

I already exchanged some mails with Nima about this problem. This Issue is for keeping Track of the problem solving process.

### Short description
I encountered this problem while running GangSTR on a subset of the regions file `hg19_ver8.bed`  including only CAG and CTG regions with standard settings (no `--genomewide` mode, but testing suggests that this does not influence the problem). The problem became apparent when taking a first look at the data and seeing a clear cut cluster of loci that deviate from the reference by ~230 with the mean of non-outliers around 0.
After some investigation I realized that all of the outliers had a GB value much larger than the right value of the confidence interval. This is not restricted to certain loci.This seems to be an erroneous behaviour of GangSTR.
  
_This Plot shows the clustering of erroneous values around 230 (DIF is the difference from the reference, POS the position on the chromosome):_
![outliers_vs_normal_perchrom](https://user-images.githubusercontent.com/26483724/44689814-6846a080-aa1e-11e8-896a-8aadb5fb7d9b.png)

The samples that we observed this behaviour for have a lower insert size than the average of our data.   
The outliers also seem to differ in the Quality value GangSTR assigns to them.  
  
![density quality outliers vs not](https://user-images.githubusercontent.com/26483724/44689279-99be6c80-aa1c-11e8-977a-3c3070bed53e.png)

During the process of putting together some data for the developers I found that the reproducibility of the error in a locus is influenced by the size of the available region surrounding it. Sub setting the .bam file to be only 1MB around the locus caused the targeted loci to have normal values. A 2MB file showed the erroneous behaviour.

Thanks for the help

Best Matthias

**Comment by nmmsv** [comment]
This issue (as a systematic error) should be resolved in our latest release.
There is still a chance for genotype to fall outside of confidence interval if there isn't enough statistical information. We suggest filtering out these regions using `--filter-badCI` with dumpSTR (https://github.com/gymreklab/GangSTR/wiki/Filtering-GangSTR-output).
Please open another issue if the problem persists.
Thanks.
