### ISSUE TITLE
GangSTR gives very high GB values. Possibly related to piling FRRs

### ISSUE THREAD

**Issue by Matthlas** [gymreklab/GangSTR#34]
Hi,

Thanks again for the great tool.  
  
I encountered another problem with GangSTR in a new run. Some loci in our data have suspiciously high GB values. Additionally there is a cluster at the highest value observed which is exactly 600. This seems rather unnatural and unlikely to me.  
  
_GB values over all samples and loci (y scale log10 transformed)_
![gt_len_histogram](https://user-images.githubusercontent.com/26483724/45969824-7b876480-bffa-11e8-9a9a-ba40bd64853a.png)

I first ran GangSTR with the standard settings providing only `--bam`, `--ref`, `--regions`  and `--out`. After that gave me strange results I tried adding the `--genomewide` flag but still got the same problem.

I think the problem might be related to some of the loci having a very high number of FRRs due to a piling of the reads at certain loci during alignment.  
  
_GB values over all samples and loci indicating FRR count > 100(y scale log10 transformed)_
![gt_len_histogram_frr 100](https://user-images.githubusercontent.com/26483724/45970607-94911500-bffc-11e8-9c83-f5a550def821.png)
There seems to be a trend of the high FRR count being correlated with a high GB value. This makes sense I guess since a larger repeat region increases the probability of producing FRRs but I am still suspicious regarding the clustering of values at 600 which makes me doubt the rest of the values too.  
  
I saw that you mention the option of specifying a list of off-target regions for each TR in the Readme. I guess that could solve that problem or at least decrease its impact. 
My question regarding that is: what's the recommended way to incorporate off-target FRRs? Should I for each locus specify all other regions with the same motif? Or filter regions with a certain Read Depth and only include those? If so did you experiment with that and have a recommended cut-of value for the Read Depth? Our median RD is 33, median FRR is 0.

_FRR count over all samples and loci(y scale log10 transformed)_
![frr_histogram](https://user-images.githubusercontent.com/26483724/45971340-6f9da180-bffe-11e8-93c9-8e5a76c58022.png)

Thanks so much for you help!

Matthias

**Comment by nmmsv** [comment]
Hi Matthias,
Thanks for reporting this issue.
Do you have off-target regions specified in your bed file?
Regardless of that, if you use --genomewide, the off-target regions should not be scanned. 
I advise checking the loci that seem to be problematic in IGV. Sometimes the flanking region around a STR locus looks similar to imperfect copies of the motif. This can cause inflation in the estimate for that region. In that case, the best approach is to not included those loci, as GangSTR requires the flanking region to be non-repetitive.

**Comment by Matthlas** [comment]
Hi Nima,
Thanks for your answer.
I did not specify any off-target regions in my bed file yet. If that might help I would like to try that though. Do you have a recommendation on how to go about that? Would you recommend specifying all regions with the same motif for each locus or filtering them by read depth or something similar and add a subset as off-target regions to all other loci?
I already checked some of the loci in IGV and the flanking regions did not look particularly similar to the repeat.  
Eg:
![igv_reads_sample24_chr1_tcc_repeat](https://user-images.githubusercontent.com/26483724/46030033-a3d69800-c0ba-11e8-846f-1f8025777699.png)
 
Thanks,
Matthias

**Comment by nmmsv** [comment]
In genomewide more, off-target regions are not scanned. So that shouldn't change anything. 
This regions seems a bit odd. It seems to have a massively inflated coverage, while it seems like there are a lot of mismatches in the aligned reads. While a large expansion could cause a fairly large inflation in coverage, it's also possible that this region is poorly assembled in the reference. We identified quite a few of these on hg19.
If you have other samples, you can compare the estimate on the same locus across samples. If it is called as expanded across your cohort, it's likely caused by an issue in the reference, and you can confidently filter this locus out.
Hope this helps! :)
