### ISSUE TITLE
hg38_ver5.bed.gz not in sorted order

### ISSUE THREAD

**Issue by jjfarrell** [gymreklab/GangSTR#36]
The hg38_ver5.bed.gz file is not in sorted order.  So when running GangSTR,  the resulting vcf output is also out of sorted order.

This will sort it into the correct order:
 bedtools sort -faidx GRCh38_full_analysis_set_plus_decoy_hla.fa.fai -i hg38_ver5.bed >hg38_ver6.bed

**Comment by nmmsv** [comment]
Hello,
Thanks for reporting this issue.
Please try the new reference (Motifs of up to 20 bps):
https://s3.amazonaws.com/gangstr/hg38_ver6.sorted.bed.gz
Please let me know if there were any issues.
Thanks.
