### ISSUE TITLE
Running in parallel by splitting hs37_ver8.bed

### ISSUE THREAD

**Issue by npatel22526** [gymreklab/GangSTR#42]
Hello, 

I split the original reference STR file in 100 small pieces to run in parallel but got an error saying "Low coverage or targeted data. Please set coverage manually' 
I believe this is due to small number of STR reference sites that I provided. Also coverage stats (i checked using -v) are little different for each run of same sample. Is there any downside to running GangSTR this way, or it's not recommended at all ?

Best, 
Nick

**Comment by nmmsv** [comment]
Hi Nick,
That error is related to the bam file. GangSTR is trying to find the coverage from a region around the first locus in the loci that you provided. In general, this shouldn't be an issue, but I'm guessing some of the loci fall near low coverage regions. A solution is to find average coverage of your bam file externally, and setting the coverage in command line for all of your 100 small pieces.
GangSTR currently assumes uniform coverage, which may not be accurate for some samples (specially in PCR amplified samples). 
Please let me know if this change didn't help.
Best,
Nima

**Comment by npatel22526** [comment]
Hello Nima, 

Thanks for quick response. My samples are PCR-free WGS so coverage should fairly uniform. I will try running it by providing coverage information manually. Update you if it gives me any error. 

Best, 
Nick
