### ISSUE TITLE
script for trimming reference repeats?

### ISSUE THREAD

**Issue by bw2** [gymreklab/GangSTR#56]
I'm experimenting with different RepeatFinder parameters. The GangSTR paper mentions

""
To avoid errors in the local realignment step of GangSTR, all repeating regions are trimmed until they no longer contain any imperfections in their first and last four copies of the motif. Next we require that the trimmed repeating region is a perfect repetition of the motif. This step ensures there are no errors in longer STRs that may pass the trimming step. Finally, we set a threshold of at least four surviving copies for motifs of length 2-8bp and at least three copies for motifs of length greater than 8bp.  
""

I found some post-filtering in
https://github.com/gymreklab/GangSTR/blob/master/reference/chr_make_reference.sh#L74-L81
but couldn't find the trimming code described above.
Would you by chance be able to share the code for this?

**Comment by nmmsv** [comment]
Hello,
Apologies for my late response.
We're currently testing a new trimming approach, but this is the last copy that should be similar to what is described in the manuscript.
(I've changed the extension to .txt to be able to upload here. Please change it to .py and run with Python2)
[perfect_trim.txt](https://github.com/gymreklab/GangSTR/files/2862139/perfect_trim.txt)
Please let me know if you would like to try the new trimming as well.
