### ISSUE TITLE
Help reading output (Genotype given in bp difference from reference)

### ISSUE THREAD

**Issue by sngo318** [gymreklab/GangSTR#60]
`chr:1         14070  .           cctccctccctc     .           .           .           END=14081;RU=cctc;REF=3            GT:DP:GB:CI:RC:Q:INS            0/0:79:3,3:3-3,3-3:63,13,0,3:4.89157:344.217,96.4342`

I was wondering why in the output the GB (Genotype given in bp difference from reference) is not a multiple of the motif length. For example, the motif cctc is 4 bp and the reference copy number is 3. Shouldn’t the genotype for a sample be a multiple of 4, whereas in this case the GB is 3 bp?

Any help would be appreciated.

Thank you

**Comment by nmmsv** [comment]
Hello,
I think this relates to an older version of GangSTR, that had an error in the VCF fields.
The GB field that you see is actually number of copies of each allele. 
We have a newer release (2.3) available, that should fix this issue.
Sorry for confusion.
Nima

**Comment by sngo318** [comment]
Thank you
