### ISSUE TITLE
reported low number of copies for the known expansion

### ISSUE THREAD

**Issue by bharatij** [gymreklab/GangSTR#69]
Hi,
I am analyzing a sample with WES with GangSTR 2.4. This sample has SCA3 repeat expansion in ATXN3 gene.  I used the --nonuniform and --targeted parameter with this WES bam and used default values for all other parameters.  The number of copies reported for the genotype by GangSTR at this loci is 19,26 which is surprisingly low. For the same loci, STRech and Expansion Hunter reported the copies which are expected in the pathogenic rage.
I am wondering if there are any other parameters I have to set up for WES. Also, are the number of reported copies are dependent on read length?
Thanks,
Bharati

**Comment by nmmsv** [comment]
Hello,
`--nonuniform` does not use coverage as part of it's genotyping. This can possibly lead to smaller genotypes if you compare it to STRetch and EH (which I think use coverage by default). If you think the coverage in the area surrounding the locus (i.e. 1-2 fragment length window) is reasonably uniform, you can try removing the `--nonuniform` to see if that helps the call. To prevent GangSTR from trying to calculate the coverage with uniform assumption, you can supply the coverage with `--coverage`.
In any case, if you can send me the vcf line (with and without `--nonuniform`), that can also help me come up with a way to produce more accurate calls.

**Comment by bharatij** [comment]
Thanks for your suggestions.   I ran the samples with and without --nonuniform parameter and then without --nonuniform and with --coverage . 
Please see the output line for 3 options
**### 1.  with --nonuniform parameter**
OUTPUT:
14      92537353        .       gctgctgctgctgctgctgctgctgctgctgct       gctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgct,gctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgct        .       .       END=92537386;RU=gct;PERIOD=3;REF=11;GRID=6,29;STUTTERUP=0.05;STUTTERDOWN=0.05;STUTTERP=0.9;EXPTHRESH=-1      GT:DP:Q:REPCN:REPCI:RC:ML:INS:STDERR:QEXP       1/2:131:0.378357:19,26:18-19,25-27:8,8,0,112:989.565:175.352,63.2532:0.270063,0.49505:-1,-1,-1

**### 2.  without -nonuniform**
OUTPUT:
14      92537353        .       gctgctgctgctgctgctgctgctgctgctgct       gctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgct,gctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgct        .       .       END=92537386;RU=gct;PERIOD=3;REF=11;GRID=6,29;STUTTERUP=0.05;STUTTERDOWN=0.05;STUTTERP=0.9;EXPTHRESH=-1      GT:DP:Q:REPCN:REPCI:RC:ML:INS:STDERR:QEXP       1/2:131:0.378357:19,26:18-19,25-27:8,8,0,112:989.565:175.352,63.2532:0.270063,0.49505:-1,-1,-1

**### 3.  without -nonuniform and with --coverage**
I calculated the mean coverage for this WES sample with Mosdepth and supplied it --coverage parameter.
OUTPUT:
14      92537353        .       gctgctgctgctgctgctgctgctgctgctgct       gctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgct,gctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgctgct        .       .       END=92537386;RU=gct;PERIOD=3;REF=11;GRID=6,29;STUTTERUP=0.05;STUTTERDOWN=0.05;STUTTERP=0.9;EXPTHRESH=-1      GT:DP:Q:REPCN:REPCI:RC:ML:INS:STDERR:QEXP       1/2:131:0.378357:19,26:18-19,25-27:8,8,0,112:989.565:175.352,63.2532:0.270063,0.49505:-1,-1,-1


I do not see any difference with each of these options. Am I missing something?

**Comment by nmmsv** [comment]
Humm they look similar to me. Is this only happening in one sample? Or are there other samples in the study?
If the dataset is publicly available, I can try to reproduce this call to see if there is anything missing on our end to make the correct call.

**Comment by bharatij** [comment]
Actually, there are other samples with the same issue. Since the samples are not publically available, unfortunately, we can not share the samples with you. 
 I would also like to check if there are any bam processing step affecting expansion detection.  Our sorted and indexed BAMs are generated using BWA-mem mapping followed by Indel realignment with GATK and duplicates marking using PICARD. 
Would it be possible for you to share the parameters you used with WES sample analysis in your study? I will run the samples with the same parameters and see if it helps.

**Comment by nmmsv** [comment]
Humm that's odd. Based on the VCF file, there are a lot of partially repetitive reads discovered, but no fully repetitive read. You can try using `--output-readinfo` to get a list of all of the extracted reads. I'm curious about the distribution of the number of copies in partially repetitive reads..

We didn't do any specific preprocessing on the WES data. The DbGaP accession for that dataset is phs000371.v1.p1.

**Comment by nmmsv** [comment]
We are currently working on improving exome calls, please let me know or reopen this issue if you had any questions in this area.
Thanks.
Nima

**Comment by bharatij** [comment]
Thanks, Nima. It will be great to see how improved version works exome calls. Keep me updated. I will give a try again.

**Comment by bharatij** [comment]
Hi Nima,
I just wanted to touch base with you regarding the improvement in exome calls. If you any update, I can try it on WES samples.
Thanks,
Bharati

**Comment by nmmsv** [comment]
Hi Bharati,
Unfortunately, we haven't had the resources to work on WES calling in the past months. Apologies! Currently, this is not in our top priorities for development.
Best,
Nima
