### ISSUE TITLE
Unable to download Target TR loci for hg38

### ISSUE THREAD

**Issue by alexandraweb** [gymreklab/GangSTR#71]
Hi, 
Would you be able to check on the links for the reference target TR regions files for hg38 - they are not working for me currently.  

hg38_ver13.bed.gz
hg38_ver12.bed.gz
hg38_ver5.bed.gz
hg38_ver6.sorted.bed.gz

Thank you!
Alex

**Comment by nmmsv** [comment]
Hi Alex,

I've fixed the broken links. Can you please try again to see if everything works?
Thank you very much for reporting this issue. 

Nima

**Comment by alexandraweb** [comment]
Hi Nima,
Yes, they are working now!

Thanks!
Alex
