### ISSUE TITLE
WARNING: Region exceeds maximum total processed reads per sample.

### ISSUE THREAD

**Issue by shenweima** [gymreklab/GangSTR#77]
A message "WARNING: Region exceeds maximum total processed reads per sample."
What is means?

**Comment by nmmsv** [comment]
Some regions of the genome accumulate many reads during the alignment process. This can slow down the genome-wide run significantly. As a result, we limit the number of reads processed per locus to avoid potentially problematic loci.
You can increase this limit by using `--max-proc-read <int>` option.
