### ISSUE TITLE
STR info example

### ISSUE THREAD

**Issue by Phillip-a-richmond** [gymreklab/GangSTR#78]
Do you have an example of an STR info file? Do the loci have to be an exact match? Do you want bed (0-based) or the 1-based coordinate scheme?

Thanks,
Phil

**Comment by nmmsv** [comment]
Hi Phil,
The str-info file uses the same coordinates as the original regions file (1-based) and the loci have to be exact match. The 

file is tab delimited and has a header similar to this:
https://github.com/gymreklab/GangSTR#--str-info

[test.txt](https://github.com/gymreklab/GangSTR/files/3643398/test.txt)
