### ISSUE TITLE
Using GangSTR on HiFi PacBio reads

### ISSUE THREAD

**Issue by Tierhon** [gymreklab/GangSTR#88]
Hi,
would GangSTR work with the PacBio HiFi reads instead of Illumina reads? We are planning to sequence some individuals and are considering getting HiFi reads for looking at structural variations and such. Could we use the same reads to look at STRs also?

Thank you.

Ole

**Comment by nmmsv** [comment]
Hi Ole,
GangSTR uses information extracted from paired-end short reads. Because of that, GangSTR won't be able to use PB HiFi to genotype TRs.
Best,
Nima
